# Generated by Django 4.0.7 on 2024-03-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porosity_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_psi', models.CharField(blank=True, max_length=100)),
                ('volume_mercury_intruded', models.CharField(blank=True, max_length=100)),
                ('cumulative_volume', models.CharField(blank=True, max_length=100)),
                ('pore_diameter_nm', models.CharField(blank=True, max_length=100)),
                ('specific_surface_area', models.CharField(blank=True, max_length=100)),
                ('avg_pore_size_nm', models.CharField(blank=True, max_length=100)),
                ('median_pore_size_nm', models.CharField(blank=True, max_length=100)),
                ('total_pore_volume', models.CharField(blank=True, max_length=100)),
                ('tortuosity', models.CharField(blank=True, max_length=100)),
                ('permeability_mDarcy', models.CharField(blank=True, max_length=100)),
                ('adsorption_capacity', models.CharField(blank=True, max_length=100)),
                ('client_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Porosity_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('por_admin_lg', models.BooleanField(default=False)),
            ],
        ),
    ]
